import React from 'react';
export const Cantadas = [
  
{area:'',frase:'Se você acredita em salvação, teria como você me salvar da solidão? '},
{area:'',frase:'Tinha dois docinhos, o brigadeiro e o beijinho. Comi o brigadeiro e qual sobrou?'},
{area:'',frase:'Eu não sou Casas Bahia, mas prometo dedicação total a você '},
{area:'',frase:'Estou fazendo uma campanha de doação de órgãos!Então, não quer doar seu coração pra mim?'},
{area:'',frase:'Papo de urubu, pena de galinha, se você quer um beijinho dê uma risadinha'},
{area:'',frase:'Se beleza fosse flor, você seria o Jardim Botânico! '},
{area:'',frase:'Não sou carro, mas sou Para ti.'},
{area:'',frase:'Vou te dar um beijo, se você não gostar me devolve.'},
{area:'',frase:'Nossa, tô sentindo uma dor no peito, espero que seja amor. Porque se for enfarto, eu nunca mais vou ver você...'},
{area:'',frase:' Tá vendo aquela estrela ali? Mandei pendurar pra você.'},
{area:'',frase:' Queria te desejar noite, porque se fosse boa, estaríamos juntos'},
{area:'',frase:' Você não é pescoço mais mexeu com a minha cabeça! '},
{area:'',frase:' Usei shampoo anti-quedas, mas continuo caindo de amores por você'},
{area:'',frase:' Nossa, você foi feita com velas, mel, fitinhas vermelhas e rosas? Porque te achei uma simpatia'},
{area:'',frase:' Crush, um mês atrás eu era apaixonado por você e parece que estamos no mês passado ainda'},
{area:'',frase:' Use aquele shampoo para esquecer o ex, ele chama Euserve'},
{area:'',frase:' Tá calor né? Mas não é de hoje que eu me derreto por você'},
{area:'',frase:' Pesquisas apontam que agente junto é erro de gramática, mas a gente separado é erro do destino'},
{area:'',frase:' O que eu sinto por você é motorista, porque passageiro não é'},
{area:'',frase:' Você sabe o número da polícia? Infelizmente, vou ter que denunciar você por roubar meu coração'},
{area:'',frase:' Nada na vida é perfeito, mas você é o que mais se aproxima da perfeição'},
{area:'',frase:' Não existe amor à primeira vista. O que existe é a pessoa certa, no momento certo. Você por acaso estava lá'},
{area:'',frase:' Existe um vazio no meu coração que tem as suas medidas. Quer entrar?'},
{area:'',frase:' Se preto fosse paixão e branco fosse carinho, o que eu sinto por você seria xadrezinho'},
{area:'',frase:' Não te doem as pernas de fugir dos meus sonhos todas as noites, meu amor?'},
{area:'',frase:' Gosto de seus olhos, porém prefiro os meus, pois se não fosse por eles eu jamais veria os seus...'},
{area:'',frase:' Se toda vez que eu fechar os olhos, ganhasse um beijo seu, fecharia os olhos eternamente! '},
{area:'',frase:' Você acredita em amor à primeira vista ou devo passar por aqui mais uma vez?'},
{area:'',frase:' Sua mãe é uma rosa e seu pai um jasmim, admiro eles porque fizeram você especialmente pra mim'},
{area:'',frase:' Pensei que ia me divertir na internet, mas parece que só cheguei aqui pra sofrer por não ser o amor dessa mulher maravilhosa'},
{area:'',frase:' Você não pode ser o meu primeiro, mas você pode ser meu último'},
{area:'',frase:' As rosas são vermelhas, violetas são azuis, eu não posso rimar, mas posso namorar você?'},
{area:'',frase:' Se você está aqui, quem está gerenciando o céu?'},
{area:'',frase:' Se você segurar 8 rosas na frente de um espelho, você verá 9 das coisas mais bonitas do mundo! '},
{area:'',frase:' Ontem eu queria te beijar. Hoje estou igual ontem'},
{area:'',frase:' Onde é que eu deixo meu currículo para concorrer a vaga de amor da sua vida?'},
{area:'',frase:' Hoje eu vou dormir com Deus. Amanhã, se Deus quiser, eu vou dormir com você'},
{area:'',frase:' Igual você, nem o Google encontra'},
{area:'',frase:' Eu não sou plano de saúde, mas se você quiser eu acabo com a sua carência.'},
{area:'',frase:' Espero que você nao tenha diabetes, porque agora eu fiquei doce, doce, doce, doce! '},
{area:'',frase:' Eu não sou o Luciano Huck, mas eu quero você no meu lar doce lar! '},
{area:'',frase:' Eu não sou Alice, mas com você me sinto no País das Maravilhas'},
{area:'',frase:' Você não é massagem cardíaca, mas toca e reanima o meu coração! '},
{area:'',frase:' Eu perdi o número do meu telefone… Me empresta o seu?'},
{area:'',frase:' Em cima da colina passa boi passa boiada, só saio da sua frente quando for minha namorada.'},
{area:'',frase:' Você não é GPS quebrado, mas me deixa sem rumo…'},
{area:'',frase:' Fica comigo que eu faço esquecer o João. Que João? Viu só, já está esquecendo…'},
{area:'',frase:' Por acaso é seu aniversário? Porque você está de parabéns'},
{area:'',frase:' Por acaso seu pai é pirata? Não, porquê? Porque você é um tesouro'},
{area:'',frase:' Você não é colesterol mais afetou meu coração…'},
{area:'',frase:' Meu amor por você é igual à obra do governo. Nunca acaba…'},
{area:'',frase:' Me passa seu Twitter? É que a minha mãe falou para eu seguir meu sonho! '},
{area:'',frase:' Sabe estacionar? Porque tem uma vaga o meu coração'},
{area:'',frase:' Pressa é sua inimiga, porque eu ouvi dizer que a pressa é inimiga da perfeição'},
{area:'',frase:' Me chama de urna eletrônica e me dá seu voto de confiança'},
{area:'',frase:' Se eu fosse um refrigerante, seria Soda, porque no meu coração soda você'},
{area:'',frase:' Sabe o que combina com você? Eu! '},
{area:'',frase:' Sua mão ficaria mais bonita encaixada na minha'},
{area:'',frase:' Eu queria ser grego, mas grego eu não posso ser, porque grego tem várias deusas e minha única deusa é você'},
{area:'',frase:' Vontade de fazer aquilo que começa com s: ser o amor da sua vida'},
{area:'',frase:' Que tudo na sua vida brilhe como seus olhos, seja maravilhoso como seu coração, e linda como você.'},
{area:'',frase:' Você sabe qual é o motivo do meu sorriso todos os dias? A primeira palavra dessa frase...'},
{area:'',frase:' Meu coração é totalmente seu e às vezes parece pequeno demais para todo amor que sinto por você! '},
{area:'',frase:' Especial é você, que me faz sorrir nos piores momentos'},
{area:'',frase:' Eu juro que eu tinha pensado em uma cantada infalível há um minuto, mas toda vez que eu chego perto de você parece que meu mundo para, eu esqueço de tudo e só consigo me concentrar nos seus olhos.'},
{area:'',frase:' O amor não é mais que poesia cantada pelo coração'},
{area:'',frase:' Já quis o mundo inteiro, mas agora percebo que esse mundo que tanto quis sempre foi você'},
{area:'',frase:' O seu sorriso é tudo que eu quero e uma chance é tudo que preciso'},
{area:'',frase:' Aprendi a tocar violão e até a escrever poesia, descobri onde nascem os mares, a paz, o amor e até a alegria. Hoje eu sei qual a origem da beleza: você.'},
{area:'',frase:' Acabei de tomar o maior susto da minha vida. Por momentos, pensei que tinha morrido e ido para o céu, pois tem um anjo na minha frente.'},
{area:'',frase:' Já imaginei como seria a nossa vida juntos muitas vezes, mas tenho certeza de que nem o mais louco dos sonhos iria se comparar com a realidade de ter você ao meu lado'},
{area:'',frase:' Um dia me perguntaram "O que você viu nela?" e eu respondi "O que faltava em mim! '},
{area:'',frase:' E tem como não sorrir quando me lembro de você?'},
{area:'',frase:' Não sei se o mundo é bom, mas ele ficou muito melhor quando você chegou'},
{area:'',frase:' Fui ver a previsão do tempo e li que vai rolar um clima entre nós'},
{area:'',frase:' Tentando capturar aquele pokemon lendário chamado seu coração'},
{area:'',frase:' Entre Star Wars e Star trek, o que eu queria mesmo era star com você'},
{area:'',frase:' Não sou o Yoshi, mas daria até minha vida por você'},
{area:'',frase:' Desativa esse firewall e deixa eu invadir seu coração'},
{area:'',frase:' Você não é o Charmander, mas me deixa pegando fogo'},
{area:'',frase:' Me chama de Mario e vem ser minha princesa Peach'},
{area:'',frase:' Meu amor é igual ao mapa de Minecraft: infinito e cheio de surpresas'},
{area:'',frase:' Você não é Death Note, mas me matou quando me escreveu pela primeira vez'},
{area:'',frase:' Se você quiser pode até me chamar de Buzz Lightyear, porque eu sou capaz de levar a nossa relação ao infinito e além'},
{area:'',frase:' Você deveria entrar em Hogwarts, porque o que você faz com o meu coração só pode ser bruxaria'},
{area:'',frase:' Se você quiser ser o meu player dois, o lugar está reservado para salvarmos vários jogos no meu coração'},
{area:'',frase:' Não sou o Stephen King, mas meu coração fica iluminado quando você olha pra mim'},
{area:'',frase:' Queria ser o Batman para que você me chamasse sempre que precisasse de alguém, mas já que não possuo batsinal, vem de Zap'},
{area:'',frase:' Você é feito de lítio, neodímio, oxigênio e carbono. Sabe por quê? Porque você é Li-Nd-O-NA'},
{area:'',frase:' Você não é Tesseract, mas é a única pessoa capaz de abrir as portas do meu coração'},
{area:'',frase:' O único intruso que eu quero na minha vida é... Você! '},
{area:'',frase:' Você é um eixo terrestre? Porque meu mundo gira em torno de você! '},
{area:'',frase:' Você é do Mortal Kombat? Porque sua beleza me deu fatality'},
{area:'',frase:' Vem ser o Mario do meu Luigi'},
{area:'',frase:' Eu sei que não sou herói da DC, mas você com certeza é a Mulher Maravilha'},
{area:'',frase:' Eu devo ter tomado um pouco de Felix Felicis… Porque estou com sorte de ter te encontrado! '},
{area:'',frase:' Oi, eu deveria ser chamado de Stark no espaço, pois eu perdi o ar quando eu te vi! '},
]
